### ISSUE TITLE
ffmpeg parameters

### ISSUE THREAD

**Issue by edasque** [formcore/x265-videoconverter#16]
Is there a way to pass parameters to ffmpeg for hardware dec/env such as: ```-b:v 700K -c:v hevc_nvenc``` ?

**Comment by samule-i** [comment]
There unfortunately is not, it could be something I want to add, but at what point does it just become writing an ffmpeg command or something like handbrake?

**Comment by thisisnotdave** [comment]
Adding some configuration options would be great, such as passing through audio instead of re-encoding it. I really like how this script works but initial results were bad quality wise. It took a ~2.2gb h.264 video file and shrunk it down to 200mb with tons of macroblocks.

**Comment by samule-i** [comment]
Not all HEVC compatable containers are compatable with all audio codecs that will be passed to it, it does attempt to pass through audio where the codec is compatable.

To reduce quality loss I need to look at putting in an option to set the quality or bitrate of ffmpegs output, I'll look into a way to implement it but it'd increase file-size and possible transcode times.

**Comment by thisisnotdave** [comment]
Thanks for your reply. I've poked around a bit and figured out how to get EAC3 to pass through, and added added a line to FFMPEG to set the CRF to 21 and got much better results. It's pretty slow to encode, only managing 1.2x or so on my Ryzen 9, but it works great! Thanks for your efforts, this is saving me a ton of time versus doing it by hand in handbrake.
